version: '3'
services:
  
   express:
     build:
       context: ./node
       dockerfile: Dockerfile.prod
     image: jaksonsneider/express:prod
     container_name: express
     entrypoint: dockerize -wait tcp://mysql:3306 -timeout 10s node server.js
     ports:
       - "3000"
     networks:
       - fullcyclenet
     depends_on:
       - mysql        

   mysql:
     image: mysql:5.7
     command: --innodb-use-native-aio=0
     container_name: db-mysql
     restart: always
     tty: true
     volumes: 
       - ./node/mysql:/var/lib/mysql
     environment:
       - MYSQL_DATABASE=nodedb
       - MYSQL_ROOT_PASSWORD=root
     networks:
       - fullcyclenet

   nginx:
     build: 
       context: ./nginx
       dockerfile: Dockerfile.prod
     image: jaksonsneider/nginx:prod
     container_name: nginx
     ports: 
       - "8080:80"
     networks: 
       - fullcyclenet
     depends_on:
      -  express

networks:
  fullcyclenet:
    driver: bridge